// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package recipes

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recipe struct {
	ID           int64
	Name         string
	Ingredients  []byte
	Instructions pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
