# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recipe_pb2 as recipe__pb2


class RecipeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecipe = channel.unary_unary(
                '/RecipeService/GetRecipe',
                request_serializer=recipe__pb2.RecipeRequest.SerializeToString,
                response_deserializer=recipe__pb2.RecipeResponse.FromString,
                )


class RecipeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecipe,
                    request_deserializer=recipe__pb2.RecipeRequest.FromString,
                    response_serializer=recipe__pb2.RecipeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecipeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecipeService/GetRecipe',
            recipe__pb2.RecipeRequest.SerializeToString,
            recipe__pb2.RecipeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
