# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recipe.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecipe.proto\"\x1c\n\rRecipeRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"J\n\x0eRecipeResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0bingredients\x18\x02 \x01(\t\x12\x14\n\x0cinstructions\x18\x03 \x01(\t2=\n\rRecipeService\x12,\n\tGetRecipe\x12\x0e.RecipeRequest\x1a\x0f.RecipeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recipe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECIPEREQUEST']._serialized_start=16
  _globals['_RECIPEREQUEST']._serialized_end=44
  _globals['_RECIPERESPONSE']._serialized_start=46
  _globals['_RECIPERESPONSE']._serialized_end=120
  _globals['_RECIPESERVICE']._serialized_start=122
  _globals['_RECIPESERVICE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
