services:
  web:
    image: cosmtrek/air:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["air", "-c", ".air.toml", "-d"]
  scraper:
    build:
      context: .
      dockerfile: cmd/scraper/Dockerfile
    volumes:
      - ./cmd/scraper:/app
    command: python index.py
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    command: tail -f /dev/null
volumes:
  db_data: